# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3a6b2125ae7e342c0da68a5910aebbfe8975eef7661a3ccf409a9be4ce6bb849f759a6c0e6ab7aae93524b120603db292c1e03763a6d06861897113af711e82

test:
  secret_key_base: 2814313ecf4d046abf485081104e5f3a96e4d5fde2ff94b52f4b8616c6c66ce39815fd083e07cd9d62910b2a922495784fdaed61f3bf58d2872b8d747b14041c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
