# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: deea804d52003139bd8a3dfb32b084a07edeb7af2255433f47842a74a6eeecb8c92e5e621fb0a6cd9c2e74f691a680a861c7175178cd8488bdc51ecb3ee8e279

test:
  secret_key_base: 83d5e4f3399329bf684c9b14bfc57593b30618a3aa53b1a52d3abbcb256e1fbac7da8876e38b8d31198de9614e481e3729f054259284093e7b96f5a0c4872346

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
